$(".back_new_color").click(function(){
    if($("#light").attr("class") == "fa-solid fa-sun"){
        $("#light").attr("class", "fa-solid fa-moon");
            $("body").css("background", "#fff");
            $("body").css("color", "#111");
            $(".offcanvas").css("background", "#fff");
            $(".navbar-toggler").css("color", "#111");
            $(".div_sbm").css("color", "#111");
    }else{
        $("#light").attr("class", "fa-solid fa-sun");
            $("body").css("background", "#232323");
            $("body").css("color", "#fff");
            $(".offcanvas").css("background", "#232323");
            $(".navbar-toggler").css("color", "#fff");
            $(".div_sbm").css("color", "#fff");
    };
});
const nkar = [
    "xozi_xorovac.jpg",
    "havi_xorovac.jpg"
];
window.onload = function(){
    var apranq = $(".apranq");
    var s = "1 Շիշ";
    var h = "1 Հատ";
    var d = "֏";
    for(var i = 0; i < apranq.length; i++){
        var xorovac = document.createElement("div");
        apranq[i].appendChild(xorovac);
        var xorovac_anun = document.createElement("div");
        $(xorovac_anun).html("Խոզի Խորոված");
        $(xorovac_anun).attr("class", "xorovaci_anun");
        xorovac.appendChild(xorovac_anun);
        var img = document.createElement("img");
        xorovac.appendChild(img);
        var nkar_div = document.createElement("div");
        xorovac.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/xozi_xorovac.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(s + ' ' + '3000' + ' ' + d);
        $(gin).attr("class", "gin");
        xorovac.appendChild(gin);
        var xorovac_mec_btn = document.createElement("div");
        xorovac.appendChild(xorovac_mec_btn);
        var xorovac_btn = document.createElement("button");
        xorovac.appendChild(xorovac_btn);
        xorovac_mec_btn.appendChild(xorovac_btn);
        $(xorovac_btn).html("Պատվիրել");
        $(xorovac_btn).attr("class", "xorovac_btn");
        $(xorovac_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq.length; i++){
        var hav = document.createElement("div");
        apranq[i].appendChild(hav);
        var hav_anun = document.createElement("div");
        $(hav_anun).html("Հավի Խորոված");
        $(hav_anun).attr("class", "xorovaci_anun");
        hav.appendChild(hav_anun);
        var img = document.createElement("img");
        hav.appendChild(img);
        var nkar_div = document.createElement("div");
        hav.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/havi_xorovac.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html('1.5 Կգ' + ' ' + '3500' + ' ' + d);
        $(gin).attr("class", "gin");
        hav.appendChild(gin);
        var hav_mec_btn = document.createElement("div");
        hav.appendChild(hav_mec_btn);
        var hav_btn = document.createElement("button");
        hav.appendChild(hav_btn);
        hav_mec_btn.appendChild(hav_btn);
        $(hav_btn).html("Պատվիրել");
        $(hav_btn).attr("class", "hav_btn");
        $(hav_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq.length; i++){
        var shaurma = document.createElement("div");
        apranq[i].appendChild(shaurma);
        var shaurma_anun = document.createElement("div");
        $(shaurma_anun).html("Շաուրմա");
        $(shaurma_anun).attr("class", "xorovaci_anun");
        shaurma.appendChild(shaurma_anun);
        var img = document.createElement("img");
        shaurma.appendChild(img);
        var nkar_div = document.createElement("div");
        shaurma.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/xozi_shaurma.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '1000' + ' ' + d);
        $(gin).attr("class", "gin");
        shaurma.appendChild(gin);
        var shaurma_mec_btn = document.createElement("div");
        shaurma.appendChild(shaurma_mec_btn);
        var shaurma_btn = document.createElement("button");
        shaurma.appendChild(shaurma_btn);
        shaurma_mec_btn.appendChild(shaurma_btn);
        $(shaurma_btn).html("Պատվիրել");
        $(shaurma_btn).attr("class", "shaurma_btn");
        $(shaurma_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq.length; i++){
        var qyabab_tavari = document.createElement("div");
        apranq[i].appendChild(qyabab_tavari);
        var qyabab_tavari_anun = document.createElement("div");
        $(qyabab_tavari_anun).html("Տավարի Քյաբաբ");
        $(qyabab_tavari_anun).attr("class", "xorovaci_anun");
        qyabab_tavari.appendChild(qyabab_tavari_anun);
        var img = document.createElement("img");
        qyabab_tavari.appendChild(img);
        var nkar_div = document.createElement("div");
        qyabab_tavari.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/tavari_qyabab.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '900' + ' ' + d);
        $(gin).attr("class", "gin");
        qyabab_tavari.appendChild(gin);
        var qyabab_tavari_mec_btn = document.createElement("div");
        qyabab_tavari.appendChild(qyabab_tavari_mec_btn);
        var qyabab_tavari_btn = document.createElement("button");
        qyabab_tavari.appendChild(qyabab_tavari_btn);
        qyabab_tavari_mec_btn.appendChild(qyabab_tavari_btn);
        $(qyabab_tavari_btn).html("Պատվիրել");
        $(qyabab_tavari_btn).attr("class", "qyabab_tavari_btn");
        $(qyabab_tavari_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq.length; i++){
        var qyabab_havi = document.createElement("div");
        apranq[i].appendChild(qyabab_havi);
        var qyabab_havi_anun = document.createElement("div");
        $(qyabab_havi_anun).html("Հավի Քյաբաբ");
        $(qyabab_havi_anun).attr("class", "xorovaci_anun");
        qyabab_havi.appendChild(qyabab_havi_anun);
        var img = document.createElement("img");
        qyabab_havi.appendChild(img);
        var nkar_div = document.createElement("div");
        qyabab_havi.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/havi_qyabab.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '800' + ' ' + d);
        $(gin).attr("class", "gin");
        qyabab_havi.appendChild(gin);
        var qyabab_havi_mec_btn = document.createElement("div");
        qyabab_havi.appendChild(qyabab_havi_mec_btn);
        var qyabab_havi_btn = document.createElement("button");
        qyabab_havi.appendChild(qyabab_havi_btn);
        qyabab_havi_mec_btn.appendChild(qyabab_havi_btn);
        $(qyabab_havi_btn).html("Պատվիրել");
        $(qyabab_havi_btn).attr("class", "qyabab_havi_btn");
        $(qyabab_havi_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq.length; i++){
        var iqibir = document.createElement("div");
        apranq[i].appendChild(iqibir);
        var iqibir_anun = document.createElement("div");
        $(iqibir_anun).html("Խոզի իքիբիր");
        $(iqibir_anun).attr("class", "xorovaci_anun");
        iqibir.appendChild(iqibir_anun);
        var img = document.createElement("img");
        iqibir.appendChild(img);
        var nkar_div = document.createElement("div");
        iqibir.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/xozi_iqibir.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '800' + ' ' + d);
        $(gin).attr("class", "gin");
        iqibir.appendChild(gin);
        var iqibir_mec_btn = document.createElement("div");
        iqibir.appendChild(iqibir_mec_btn);
        var iqibir_btn = document.createElement("button");
        iqibir.appendChild(iqibir_btn);
        iqibir_mec_btn.appendChild(iqibir_btn);
        $(iqibir_btn).html("Պատվիրել");
        $(iqibir_btn).attr("class", "iqibir_btn");
        $(iqibir_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq.length; i++){
        var sendvich = document.createElement("div");
        apranq[i].appendChild(sendvich);
        var sendvich_anun = document.createElement("div");
        $(sendvich_anun).html("Սենդվիչ");
        $(sendvich_anun).attr("class", "xorovaci_anun");
        sendvich.appendChild(sendvich_anun);
        var img = document.createElement("img");
        sendvich.appendChild(img);
        var nkar_div = document.createElement("div");
        sendvich.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/sendvich.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '500' + ' ' + d);
        $(gin).attr("class", "gin");
        sendvich.appendChild(gin);
        var sendvich_mec_btn = document.createElement("div");
        sendvich.appendChild(sendvich_mec_btn);
        var sendvich_btn = document.createElement("button");
        sendvich.appendChild(sendvich_btn);
        sendvich_mec_btn.appendChild(sendvich_btn);
        $(sendvich_btn).html("Պատվիրել");
        $(sendvich_btn).attr("class", "sendvich_btn");
        $(sendvich_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq.length; i++){
        var plech = document.createElement("div");
        $(plech).attr("class", "plech_mec_div");
        var pakox_sptak = document.createElement("div");
        plech.appendChild(pakox_sptak);
        $(pakox_sptak).attr("class", "pakox_spitak");
        apranq[i].appendChild(plech);
        var plech_anun = document.createElement("div");
        $(plech_anun).html("Կարտոֆիլի պլեչ");
        $(plech_anun).attr("class", "xorovaci_anun");
        plech.appendChild(plech_anun);
        var img = document.createElement("img");
        plech.appendChild(img);
        var nkar_div = document.createElement("div");
        plech.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/kartoshki_plech.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(s + ' ' + '500' + ' ' + d);
        $(gin).attr("class", "gin");
        plech.appendChild(gin);
        var plech_mec_btn = document.createElement("div");
        plech.appendChild(plech_mec_btn);
        var plech_btn = document.createElement("button");
        plech.appendChild(plech_btn);
        plech_mec_btn.appendChild(plech_btn);
        $(plech_btn).html("Պատվիրել");
        $(plech_btn).attr("class", "plech_btn");
        $(plech_mec_btn).attr("class", "xorovac_mec_btn");
    };
    var apranq2 = $(".apranq_erku");
    for(var i = 0; i < apranq2.length; i++){
        var hot_dog = document.createElement("div");
        apranq2[i].appendChild(hot_dog);
        var hot_dog_anun = document.createElement("div");
        $(hot_dog_anun).html("Հոթ - դոգ");
        $(hot_dog_anun).attr("class", "xorovaci_anun");
        hot_dog.appendChild(hot_dog_anun);
        var img = document.createElement("img");
        hot_dog.appendChild(img);
        var nkar_div = document.createElement("div");
        hot_dog.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/hot_dog.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '250' + ' ' + d);
        $(gin).attr("class", "gin");
        hot_dog.appendChild(gin);
        var hot_dog_mec_btn = document.createElement("div");
        hot_dog.appendChild(hot_dog_mec_btn);
        var hot_dog_btn = document.createElement("button");
        hot_dog.appendChild(hot_dog_btn);
        hot_dog_mec_btn.appendChild(hot_dog_btn);
        $(hot_dog_btn).html("Պատվիրել");
        $(hot_dog_btn).attr("class", "hot_dog_btn");
        $(hot_dog_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq2.length; i++){
        var axcan = document.createElement("div");
        apranq2[i].appendChild(axcan);
        var axcan_anun = document.createElement("div");
        $(axcan_anun).html("Աղցան ամառային");
        $(axcan_anun).attr("class", "xorovaci_anun");
        axcan.appendChild(axcan_anun);
        var img = document.createElement("img");
        axcan.appendChild(img);
        var nkar_div = document.createElement("div");
        axcan.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/axcan_amarayin.png';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '500' + ' ' + d);
        $(gin).attr("class", "gin");
        axcan.appendChild(gin);
        var axcan_mec_btn = document.createElement("div");
        axcan.appendChild(axcan_mec_btn);
        var axcan_btn = document.createElement("button");
        axcan.appendChild(axcan_btn);
        axcan_mec_btn.appendChild(axcan_btn);
        $(axcan_btn).html("Պատվիրել");
        $(axcan_btn).attr("class", "axcan_btn");
        $(axcan_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq2.length; i++){
        var cola = document.createElement("div");
        apranq2[i].appendChild(cola);
        var cola_anun = document.createElement("div");
        $(cola_anun).html("Կոկա Կոլա 0.5լ");
        $(cola_anun).attr("class", "xorovaci_anun");
        cola.appendChild(cola_anun);
        var img = document.createElement("img");
        cola.appendChild(img);
        var nkar_div = document.createElement("div");
        cola.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/cola.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '350' + ' ' + d);
        $(gin).attr("class", "gin");
        cola.appendChild(gin);
        var cola_mec_btn = document.createElement("div");
        cola.appendChild(cola_mec_btn);
        var cola_btn = document.createElement("button");
        cola.appendChild(cola_btn);
        cola_mec_btn.appendChild(cola_btn);
        $(cola_btn).html("Պատվիրել");
        $(cola_btn).attr("class", "cola_btn");
        $(cola_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq2.length; i++){
        var fanta = document.createElement("div");
        apranq2[i].appendChild(fanta);
        var fanta_anun = document.createElement("div");
        $(fanta_anun).html("Ֆանտա 0.5լ");
        $(fanta_anun).attr("class", "xorovaci_anun");
        fanta.appendChild(fanta_anun);
        var img = document.createElement("img");
        fanta.appendChild(img);
        var nkar_div = document.createElement("div");
        fanta.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/fanta.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '350' + ' ' + d);
        $(gin).attr("class", "gin");
        fanta.appendChild(gin);
        var fanta_mec_btn = document.createElement("div");
        fanta.appendChild(fanta_mec_btn);
        var fanta_btn = document.createElement("button");
        fanta.appendChild(fanta_btn);
        fanta_mec_btn.appendChild(fanta_btn);
        $(fanta_btn).html("Պատվիրել");
        $(fanta_btn).attr("class", "fanta_btn");
        $(fanta_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq2.length; i++){
        var sprite = document.createElement("div");
        apranq2[i].appendChild(sprite);
        var sprite_anun = document.createElement("div");
        $(sprite_anun).html("Սփրայթ 0.5լ");
        $(sprite_anun).attr("class", "xorovaci_anun");
        sprite.appendChild(sprite_anun);
        var img = document.createElement("img");
        sprite.appendChild(img);
        var nkar_div = document.createElement("div");
        sprite.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/sprite.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '350' + ' ' + d);
        $(gin).attr("class", "gin");
        sprite.appendChild(gin);
        var sprite_mec_btn = document.createElement("div");
        sprite.appendChild(sprite_mec_btn);
        var sprite_btn = document.createElement("button");
        sprite.appendChild(sprite_btn);
        sprite_mec_btn.appendChild(sprite_btn);
        $(sprite_btn).html("Պատվիրել");
        $(sprite_btn).attr("class", "sprite_btn");
        $(sprite_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq2.length; i++){
        var dobri = document.createElement("div");
        apranq2[i].appendChild(dobri);
        var dobri_anun = document.createElement("div");
        $(dobri_anun).html("Դոբրի 330մլ");
        $(dobri_anun).attr("class", "xorovaci_anun");
        dobri.appendChild(dobri_anun);
        var img = document.createElement("img");
        dobri.appendChild(img);
        var nkar_div = document.createElement("div");
        dobri.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/dobri.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '300' + ' ' + d);
        $(gin).attr("class", "gin");
        dobri.appendChild(gin);
        var dobri_mec_btn = document.createElement("div");
        dobri.appendChild(dobri_mec_btn);
        var dobri_btn = document.createElement("button");
        dobri.appendChild(dobri_btn);
        dobri_mec_btn.appendChild(dobri_btn);
        $(dobri_btn).html("Պատվիրել");
        $(dobri_btn).attr("class", "dobri_btn");
        $(dobri_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq2.length; i++){
        var fuze_tea = document.createElement("div");
        apranq2[i].appendChild(fuze_tea);
        var fuze_tea_anun = document.createElement("div");
        $(fuze_tea_anun).html("Ֆյուզ թեյ 0.5լ");
        $(fuze_tea_anun).attr("class", "xorovaci_anun");
        fuze_tea.appendChild(fuze_tea_anun);
        var img = document.createElement("img");
        fuze_tea.appendChild(img);
        var nkar_div = document.createElement("div");
        fuze_tea.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/fuze_tea.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '500' + ' ' + d);
        $(gin).attr("class", "gin");
        fuze_tea.appendChild(gin);
        var fuze_tea_mec_btn = document.createElement("div");
        fuze_tea.appendChild(fuze_tea_mec_btn);
        var fuze_tea_btn = document.createElement("button");
        fuze_tea.appendChild(fuze_tea_btn);
        fuze_tea_mec_btn.appendChild(fuze_tea_btn);
        $(fuze_tea_btn).html("Պատվիրել");
        $(fuze_tea_btn).attr("class", "fuze_tea_btn");
        $(fuze_tea_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq2.length; i++){
        var purply = document.createElement("div");
        apranq2[i].appendChild(purply);
        var purply_anun = document.createElement("div");
        $(purply_anun).html("Փալփի 0.5լ");
        $(purply_anun).attr("class", "xorovaci_anun");
        purply.appendChild(purply_anun);
        var img = document.createElement("img");
        purply.appendChild(img);
        var nkar_div = document.createElement("div");
        purply.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/pulpy.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '500' + ' ' + d);
        $(gin).attr("class", "gin");
        purply.appendChild(gin);
        purply_mec_btn = document.createElement("div");
        purply.appendChild(purply_mec_btn);
        purply_btn = document.createElement("button");
        purply.appendChild(purply_btn);
        purply_mec_btn.appendChild(purply_btn);
        $(purply_btn).html("Պատվիրել");
        $(purply_btn).attr("class", "purply_btn");
        $(purply_mec_btn).attr("class", "xorovac_mec_btn");
    };
    var apranq3 = $(".apranq_ereq");
    for(var i = 0; i < apranq3.length; i++){
        var bon_aqua = document.createElement("div");
        apranq3[i].appendChild(bon_aqua);
        var bon_aqua_anun = document.createElement("div");
        $(bon_aqua_anun).html("Բոն ակվա 0.5լ");
        $(bon_aqua_anun).attr("class", "xorovaci_anun");
        bon_aqua.appendChild(bon_aqua_anun);
        var img = document.createElement("img");
        bon_aqua.appendChild(img);
        var nkar_div = document.createElement("div");
        bon_aqua.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/bon_aqua.png';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '200' + ' ' + d);
        $(gin).attr("class", "gin");
        bon_aqua.appendChild(gin);
        bon_aqua_mec_btn = document.createElement("div");
        bon_aqua.appendChild(bon_aqua_mec_btn);
        bon_aqua_btn = document.createElement("button");
        bon_aqua.appendChild(bon_aqua_btn);
        bon_aqua_mec_btn.appendChild(bon_aqua_btn);
        $(bon_aqua_btn).html("Պատվիրել");
        $(bon_aqua_btn).attr("class", "bon_aqua_btn");
        $(bon_aqua_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq3.length; i++){
        var kola_1l = document.createElement("div");
        apranq3[i].appendChild(kola_1l);
        var kola_1l_anun = document.createElement("div");
        $(kola_1l_anun).html("Կոկա Կոլա 1լ");
        $(kola_1l_anun).attr("class", "xorovaci_anun");
        kola_1l.appendChild(kola_1l_anun);
        var img = document.createElement("img");
        kola_1l.appendChild(img);
        var nkar_div = document.createElement("div");
        kola_1l.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/cola_1l.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '500' + ' ' + d);
        $(gin).attr("class", "gin");
        kola_1l.appendChild(gin);
        kola_1l_mec_btn = document.createElement("div");
        kola_1l.appendChild(kola_1l_mec_btn);
        kola_1l_btn = document.createElement("button");
        kola_1l.appendChild(kola_1l_btn);
        kola_1l_mec_btn.appendChild(kola_1l_btn);
        $(kola_1l_btn).html("Պատվիրել");
        $(kola_1l_btn).attr("class", "kola_1l_btn");
        $(kola_1l_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq3.length; i++){
        var fanta_eqsetik = document.createElement("div");
        apranq3[i].appendChild(fanta_eqsetik);
        var fanta_eqsetik_anun = document.createElement("div");
        $(fanta_eqsetik_anun).html("Ֆանտա էկզոտիկ 0.5լ");
        $(fanta_eqsetik_anun).attr("class", "xorovaci_anun");
        fanta_eqsetik.appendChild(fanta_eqsetik_anun);
        var img = document.createElement("img");
        fanta_eqsetik.appendChild(img);
        var nkar_div = document.createElement("div");
        fanta_eqsetik.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/fanta_eqsitik.webp';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '350' + ' ' + d);
        $(gin).attr("class", "gin");
        fanta_eqsetik.appendChild(gin);
        fanta_eqsetik_mec_btn = document.createElement("div");
        fanta_eqsetik.appendChild(fanta_eqsetik_mec_btn);
        fanta_eqsetik_btn = document.createElement("button");
        fanta_eqsetik.appendChild(fanta_eqsetik_btn);
        fanta_eqsetik_mec_btn.appendChild(fanta_eqsetik_btn);
        $(fanta_eqsetik_btn).html("Պատվիրել");
        $(fanta_eqsetik_btn).attr("class", "fanta_eqsetik_btn");
        $(fanta_eqsetik_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq3.length; i++){
        var macnabrdosh = document.createElement("div");
        apranq3[i].appendChild(macnabrdosh);
        var macnabrdosh_anun = document.createElement("div");
        $(macnabrdosh_anun).html("Մածնաբրդոշ 0.5լ");
        $(macnabrdosh_anun).attr("class", "xorovaci_anun");
        macnabrdosh.appendChild(macnabrdosh_anun);
        var img = document.createElement("img");
        macnabrdosh.appendChild(img);
        var nkar_div = document.createElement("div");
        macnabrdosh.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/macnabrdosh.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '300' + ' ' + d);
        $(gin).attr("class", "gin");
        macnabrdosh.appendChild(gin);
        macnabrdosh_mec_btn = document.createElement("div");
        macnabrdosh.appendChild(macnabrdosh_mec_btn);
        macnabrdosh_btn = document.createElement("button");
        macnabrdosh.appendChild(macnabrdosh_btn);
        macnabrdosh_mec_btn.appendChild(macnabrdosh_btn);
        $(macnabrdosh_btn).html("Պատվիրել");
        $(macnabrdosh_btn).attr("class", "macnabrdosh_btn");
        $(macnabrdosh_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq3.length; i++){
        var tan = document.createElement("div");
        apranq3[i].appendChild(tan);
        var tan_anun = document.createElement("div");
        $(tan_anun).html("Թան Չգազավորված 0.5լ");
        $(tan_anun).attr("class", "xorovaci_anun");
        tan.appendChild(tan_anun);
        var img = document.createElement("img");
        tan.appendChild(img);
        var nkar_div = document.createElement("div");
        tan.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/tan.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '250' + ' ' + d);
        $(gin).attr("class", "gin");
        tan.appendChild(gin);
        tan_mec_btn = document.createElement("div");
        tan.appendChild(tan_mec_btn);
        tan_btn = document.createElement("button");
        tan.appendChild(tan_btn);
        tan_mec_btn.appendChild(tan_btn);
        $(tan_btn).html("Պատվիրել");
        $(tan_btn).attr("class", "tan_btn");
        $(tan_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq3.length; i++){
        var kotayq = document.createElement("div");
        apranq3[i].appendChild(kotayq);
        var kotayq_anun = document.createElement("div");
        $(kotayq_anun).html("Գարեջուր կոտայք 0.5լ");
        $(kotayq_anun).attr("class", "xorovaci_anun");
        kotayq.appendChild(kotayq_anun);
        var img = document.createElement("img");
        kotayq.appendChild(img);
        var nkar_div = document.createElement("div");
        kotayq.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div kotayq_nkar");
        var randomimg = '../img/kotayq.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '500' + ' ' + d);
        $(gin).attr("class", "gin");
        kotayq.appendChild(gin);
        kotayq_mec_btn = document.createElement("div");
        kotayq.appendChild(kotayq_mec_btn);
        kotayq_btn = document.createElement("button");
        kotayq.appendChild(kotayq_btn);
        kotayq_mec_btn.appendChild(kotayq_btn);
        $(kotayq_btn).html("Պատվիրել");
        $(kotayq_btn).attr("class", "kotayq_btn");
        $(kotayq_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq3.length; i++){
        var kilikia = document.createElement("div");
        apranq3[i].appendChild(kilikia);
        var kilikia_anun = document.createElement("div");
        $(kilikia_anun).html("Գարեջուր կիլիկիա 0.5լ");
        $(kilikia_anun).attr("class", "xorovaci_anun");
        kilikia.appendChild(kilikia_anun);
        var img = document.createElement("img");
        kilikia.appendChild(img);
        var nkar_div = document.createElement("div");
        kilikia.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div kilikia_nkar");
        var randomimg = '../img/kilikia.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '500' + ' ' + d);
        $(gin).attr("class", "gin");
        kilikia.appendChild(gin);
        kilikia_mec_btn = document.createElement("div");
        kilikia.appendChild(kilikia_mec_btn);
        kilikia_btn = document.createElement("button");
        kilikia.appendChild(kilikia_btn);
        kilikia_mec_btn.appendChild(kilikia_btn);
        $(kilikia_btn).html("Պատվիրել");
        $(kilikia_btn).attr("class", "kilikia_btn");
        $(kilikia_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq3.length; i++){
        var baltika9 = document.createElement("div");
        apranq3[i].appendChild(baltika9);
        var baltika9_anun = document.createElement("div");
        $(baltika9_anun).html("Գարեջուր բալտիկա (9) 0.5լ");
        $(baltika9_anun).attr("class", "xorovaci_anun");
        baltika9.appendChild(baltika9_anun);
        var img = document.createElement("img");
        baltika9.appendChild(img);
        var nkar_div = document.createElement("div");
        baltika9.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div kilikia_nkar");
        var randomimg = '../img/baltika9.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '700' + ' ' + d);
        $(gin).attr("class", "gin");
        baltika9.appendChild(gin);
        baltika9_mec_btn = document.createElement("div");
        baltika9.appendChild(baltika9_mec_btn);
        baltika9_btn = document.createElement("button");
        baltika9.appendChild(baltika9_btn);
        baltika9_mec_btn.appendChild(baltika9_btn);
        $(baltika9_btn).html("Պատվիրել");
        $(baltika9_btn).attr("class", "baltika9_btn");
        $(baltika9_mec_btn).attr("class", "xorovac_mec_btn");
    };
    var apranq4 = $(".apranq_chors");
    for(var i = 0; i < apranq4.length; i++){
        var baltika7 = document.createElement("div");
        apranq4[i].appendChild(baltika7);
        var baltika7_anun = document.createElement("div");
        $(baltika7_anun).html("Գարեջուր բալտիկա (7) 0.5լ");
        $(baltika7_anun).attr("class", "xorovaci_anun");
        baltika7.appendChild(baltika7_anun);
        var img = document.createElement("img");
        baltika7.appendChild(img);
        var nkar_div = document.createElement("div");
        baltika7.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div kilikia_nkar");
        var randomimg = '../img/baltika7.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '700' + ' ' + d);
        $(gin).attr("class", "gin");
        baltika7.appendChild(gin);
        baltika7_mec_btn = document.createElement("div");
        baltika7.appendChild(baltika7_mec_btn);
        baltika7_btn = document.createElement("button");
        baltika7.appendChild(baltika7_btn);
        baltika7_mec_btn.appendChild(baltika7_btn);
        $(baltika7_btn).html("Պատվիրել");
        $(baltika7_btn).attr("class", "baltika7_btn");
        $(baltika7_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq4.length; i++){
        var baltika3 = document.createElement("div");
        apranq4[i].appendChild(baltika3);
        var baltika3_anun = document.createElement("div");
        $(baltika3_anun).html("Գարեջուր բալտիկա (3) 0.5լ");
        $(baltika3_anun).attr("class", "xorovaci_anun");
        baltika3.appendChild(baltika3_anun);
        var img = document.createElement("img");
        baltika3.appendChild(img);
        var nkar_div = document.createElement("div");
        baltika3.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div kilikia_nkar");
        var randomimg = '../img/baltika3.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '700' + ' ' + d);
        $(gin).attr("class", "gin");
        baltika3.appendChild(gin);
        baltika3_mec_btn = document.createElement("div");
        baltika3.appendChild(baltika3_mec_btn);
        baltika3_btn = document.createElement("button");
        baltika3.appendChild(baltika3_btn);
        baltika3_mec_btn.appendChild(baltika3_btn);
        $(baltika3_btn).html("Պատվիրել");
        $(baltika3_btn).attr("class", "baltika3_btn");
        $(baltika3_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq4.length; i++){
        var tuborg = document.createElement("div");
        apranq4[i].appendChild(tuborg);
        var tuborg_anun = document.createElement("div");
        $(tuborg_anun).html("Գարեջուր տուբորգ 0.5լ");
        $(tuborg_anun).attr("class", "xorovaci_anun");
        tuborg.appendChild(tuborg_anun);
        var img = document.createElement("img");
        tuborg.appendChild(img);
        var nkar_div = document.createElement("div");
        tuborg.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div kilikia_nkar");
        var randomimg = '../img/tuborg.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '700' + ' ' + d);
        $(gin).attr("class", "gin");
        tuborg.appendChild(gin);
        tuborg_mec_btn = document.createElement("div");
        tuborg.appendChild(tuborg_mec_btn);
        tuborg_btn = document.createElement("button");
        tuborg.appendChild(tuborg_btn);
        tuborg_mec_btn.appendChild(tuborg_btn);
        $(tuborg_btn).html("Պատվիրել");
        $(tuborg_btn).attr("class", "tuborg_btn");
        $(tuborg_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq4.length; i++){
        var bjni = document.createElement("div");
        $(bjni).attr("class", "bjni_mec_div");
        apranq4[i].appendChild(bjni);
        var bjni_anun = document.createElement("div");
        $(bjni_anun).html("Բջնի 0.5լ");
        $(bjni_anun).attr("class", "xorovaci_anun");
        bjni.appendChild(bjni_anun);
        var img = document.createElement("img");
        bjni.appendChild(img);
        var nkar_div = document.createElement("div");
        bjni.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/bjni.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '250' + ' ' + d);
        $(gin).attr("class", "gin");
        bjni.appendChild(gin);
        bjni_mec_btn = document.createElement("div");
        bjni.appendChild(bjni_mec_btn);
        bjni_btn = document.createElement("button");
        bjni.appendChild(bjni_btn);
        bjni_mec_btn.appendChild(bjni_btn);
        $(bjni_btn).html("Պատվիրել");
        $(bjni_btn).attr("class", "bjni_btn");
        $(bjni_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq4.length; i++){
        var bjni_1l = document.createElement("div");
        apranq4[i].appendChild(bjni_1l);
        var bjni_1l_anun = document.createElement("div");
        $(bjni_1l_anun).html("Բջնի 1լ");
        $(bjni_1l_anun).attr("class", "xorovaci_anun");
        bjni_1l.appendChild(bjni_1l_anun);
        var img = document.createElement("img");
        bjni_1l.appendChild(img);
        var nkar_div = document.createElement("div");
        bjni_1l.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/bjni_1l.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '350' + ' ' + d);
        $(gin).attr("class", "gin");
        bjni_1l.appendChild(gin);
        bjni_1l_mec_btn = document.createElement("div");
        bjni_1l.appendChild(bjni_1l_mec_btn);
        bjni_1l_btn = document.createElement("button");
        bjni_1l.appendChild(bjni_1l_btn);
        bjni_1l_mec_btn.appendChild(bjni_1l_btn);
        $(bjni_1l_btn).html("Պատվիրել");
        $(bjni_1l_btn).attr("class", "bjni_1l_btn");
        $(bjni_1l_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq4.length; i++){
        var jur_noy = document.createElement("div");
        apranq4[i].appendChild(jur_noy);
        var jur_noy_anun = document.createElement("div");
        $(jur_noy_anun).html("Ջուր նոյ 0.5լ");
        $(jur_noy_anun).attr("class", "xorovaci_anun");
        jur_noy.appendChild(jur_noy_anun);
        var img = document.createElement("img");
        jur_noy.appendChild(img);
        var nkar_div = document.createElement("div");
        jur_noy.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/jur_noy.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '200' + ' ' + d);
        $(gin).attr("class", "gin");
        jur_noy.appendChild(gin);
        jur_noy_mec_btn = document.createElement("div");
        jur_noy.appendChild(jur_noy_mec_btn);
        jur_noy_btn = document.createElement("button");
        jur_noy.appendChild(jur_noy_btn);
        jur_noy_mec_btn.appendChild(jur_noy_btn);
        $(jur_noy_btn).html("Պատվիրել");
        $(jur_noy_btn).attr("class", "jur_noy_btn");
        $(jur_noy_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq4.length; i++){
        var tan_bajakov = document.createElement("div");
        apranq4[i].appendChild(tan_bajakov);
        var tan_bajakov_anun = document.createElement("div");
        $(tan_bajakov_anun).html("Թան բաժակով");
        $(tan_bajakov_anun).attr("class", "xorovaci_anun");
        tan_bajakov.appendChild(tan_bajakov_anun);
        var img = document.createElement("img");
        tan_bajakov.appendChild(img);
        var nkar_div = document.createElement("div");
        tan_bajakov.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/tan_bajakov.webp';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '150' + ' ' + d);
        $(gin).attr("class", "gin");
        tan_bajakov.appendChild(gin);
        tan_bajakov_mec_btn = document.createElement("div");
        tan_bajakov.appendChild(tan_bajakov_mec_btn);
        tan_bajakov_btn = document.createElement("button");
        tan_bajakov.appendChild(tan_bajakov_btn);
        tan_bajakov_mec_btn.appendChild(tan_bajakov_btn);
        $(tan_bajakov_btn).html("Պատվիրել");
        $(tan_bajakov_btn).attr("class", "tan_bajakov_btn");
        $(tan_bajakov_mec_btn).attr("class", "xorovac_mec_btn");
    };
    for(var i = 0; i < apranq4.length; i++){
        var tan_gazov = document.createElement("div");
        apranq4[i].appendChild(tan_gazov);
        var tan_gazov_anun = document.createElement("div");
        $(tan_gazov_anun).html("Թան Գազավորված 0.5լ");
        $(tan_gazov_anun).attr("class", "xorovaci_anun");
        tan_gazov.appendChild(tan_gazov_anun);
        var img = document.createElement("img");
        tan_gazov.appendChild(img);
        var nkar_div = document.createElement("div");
        tan_gazov.appendChild(nkar_div);
        nkar_div.appendChild(img);
        $(nkar_div).attr("class", "nkar_div");
        var randomimg = '../img/tan_gazov.jpg';
        $(img).attr("src", randomimg);
        $(img).attr("class", "img-fluid w-100");
        var gin = document.createElement("div");
        $(gin).html(h + ' ' + '250' + ' ' + d);
        $(gin).attr("class", "gin");
        tan_gazov.appendChild(gin);
        tan_gazov_mec_btn = document.createElement("div");
        tan_gazov.appendChild(tan_gazov_mec_btn);
        tan_gazov_btn = document.createElement("button");
        tan_gazov.appendChild(tan_gazov_btn);
        tan_gazov_mec_btn.appendChild(tan_gazov_btn);
        $(tan_gazov_btn).html("Պատվիրել");
        $(tan_gazov_btn).attr("class", "tan_gazov_btn");
        $(tan_gazov_mec_btn).attr("class", "xorovac_mec_btn");
    };

    $(".xorovac_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(xorovac_anun).html());
    });
    $(".hav_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(hav_anun).html());
    });
    $(".shaurma_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(shaurma_anun).html());
    });
    $(".qyabab_tavari_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(qyabab_tavari_anun).html());
    });
    $(".qyabab_havi_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(qyabab_havi_anun).html());
    });
    $(".iqibir_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(iqibir_anun).html());
    });
    $(".plech_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(plech_anun).html());
    });
    $(".sendvich_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(sendvich_anun).html());
    });
    $(".hot_dog_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(hot_dog_anun).html());
    });
    $(".axcan_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(axcan_anun).html());
    });
    $(".cola_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(cola_anun).html());
    });
    $(".fanta_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(fanta_anun).html());
    });
    $(".sprite_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(sprite_anun).html());
    });
    $(".dobri_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(dobri_anun).html());
    });
    $(".fuze_tea_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(fuze_tea_anun).html());
    });
    $(".purply_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(purply_anun).html());
    });
    $(".bon_aqua_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(bon_aqua_anun).html());
    });
    $(".kola_1l_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(kola_1l_anun).html());
    });
    $(".fanta_eqsetik_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(fanta_eqsetik_anun).html());
    });
    $(".macnabrdosh_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(macnabrdosh_anun).html());
    });
    $(".tan_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(tan_anun).html());
    });
    $(".kotayq_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(kotayq_anun).html());
    });
    $(".kilikia_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(kilikia_anun).html());
    });
    $(".baltika9_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(baltika9_anun).html());
    });
    $(".baltika7_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(baltika7_anun).html());
    });
    $(".baltika3_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(baltika3_anun).html());
    });
    $(".tuborg_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(tuborg_anun).html());
    });
    $(".bjni_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(bjni_anun).html());
    });
    $(".bjni_1l_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(bjni_1l_anun).html());
    });
    $(".jur_noy_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(jur_noy_anun).html());
    });
    $(".tan_bajakov_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(tan_bajakov_anun).html());
    });
    $(".tan_gazov_btn").click(function(){
        $(".form_pat").css("display", "block");
        $(".apranqatesak").val($(tan_gazov_anun).html());
    });

    if($(".form_pat").css == "display", "block"){
        $(".for_close h2").click(function(){
            $(".form_pat").css("display", "none");
        });
    };
};

document.addEventListener("contextmenu", function (e){
    e.preventDefault();
}, false);

$(document).keydown(function (event) {
    if (event.keyCode == 123) { // Prevent F12
        return false;
    } else if (event.ctrlKey && event.shiftKey && event.keyCode == 73) {
        return false;
    }
});